[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
